-- Create the table for event registrations
create table ctrl_loleventreg (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  college text not null,
  course text not null,
  year_of_study text not null,
  participated_before boolean not null,
  meme_category text not null,
  social_media text,
  transaction_id text not null,
  transaction_screenshot_url text not null,
  event_name text not null,
  consent boolean not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: You also need to create a Storage Bucket named 'payment_proofs'
-- Go to Storage -> New Bucket -> Name: 'payment_proofs' -> Public: ON
